
import type { Metadata } from "next";
import "./globals.css";
import ProviderState from "./Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
       
        <html lang="en">
        <body>
          <main> 
        <ProviderState>
        {children}
        </ProviderState>
        
        </main>
        </body>
      </html>
  );
}
